package ua.training.model.exception;

/**
 * This exception is thrown while trying to process completed invoice.
 * @author Oleksii Sevchenko
 * @see ua.training.model.dao.jdbc.JdbcInvoiceDao
 */
public class CompletedInvoiceException extends Exception {
}
